KG_EXTRACTION_PROMPT = (
    "Build a compact knowledge graph from the text below. Return at most {max_triplets} relationships and include every referenced node.\n"
    "---------------------\n"
    "TARGET OBJECTS:\n"
    "- Create Node objects for distinct entities or concepts. Each node should have a label, a name, and optional string properties.\n"
    "- Create Relationship objects for meaningful links between nodes. Each relationship should have a source name, a target name, a label, and optional string properties.\n"
    "- Ensure all relationship endpoints refer to nodes that are present in the graph.\n"
    "\n"
    "FIELD DEFINITIONS:\n"
    "- Node label: node TYPE or ontology category, for example 'Person', 'Concept', 'Organization', or 'Place'.\n"
    "- Node name: canonical human-readable name of that specific node instance. Within one extraction result, this name is also the temporary reference used by relationships.\n"
    "- Relationship source and target: they must match node names exactly, never labels.\n"
    "- Relationship label: short verb-like connector such as 'invented', 'studied', or 'located_in'.\n"
    "\n"
    "ONTOLOGY HINTS:\n"
    "Allowed node labels: {allowed_entity_types}\n"
    "Allowed relationship labels: {allowed_relation_types}\n"
    "If either list is empty, null, or unspecified, infer short, readable labels from the passage itself.\n"
    "If labels are provided, prefer them when they fit, but add a new label when the text clearly requires it.\n"
    "\n"
    "RULES:\n"
    "- Keep labels and names separate. Do not put a person name in label, and do not use a generic type like 'Person' as the name.\n"
    "- Create one node per distinct entity or concept; reuse the exact same node name instead of creating duplicate variants.\n"
    "- Node names must be unique within one extraction result.\n"
    "- Keep node names specific but concise.\n"
    "- Use relationship labels as verb-like connectors, for example 'discovered', 'located_in', or 'studied'.\n"
    "- Never use reserved system labels '__chunk__', '__document__', or '__memory__' in this extractor. Those labels are for internal system nodes created by application code.\n"
    "- Store only short factual details in properties. Do not output properties when nothing useful is available.\n"
    "- Omit weak, speculative, or redundant edges.\n"
    "- If the passage does not support a useful graph, return an empty KnowledgeGraph rather than inventing facts.\n"
    "\n"
    "EXAMPLE:\n"
    "Text: In 1911, Marie Curie received the Nobel Prize in Chemistry for her work on radium and polonium. Her research was carried out in Paris.\n"
    "Expected graph:\n"
    "- Node example: label='Person', name='Marie Curie'.\n"
    "- Node example: label='Award', name='Nobel Prize in Chemistry'.\n"
    "- Bad node example: label='Marie Curie', name='Person'.\n"
    "- Relationships should use node names as endpoints, for example source='Marie Curie', target='Nobel Prize in Chemistry', label='received'.\n"
    "- Additional nodes may represent radium, polonium, and Paris.\n"
    "- Include the year 1911 as a short property where it is useful.\n"
    "---------------------\n"
)
